worldbook/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
]

worldbook/cart/urls.py
from django.urls import path
from .views import CartDetailView, CartAddView, CartRemoveView


app_name = 'cart'
urlpatterns = [
    path('', CartDetailView.as_view(), name='cart'),
    path('add/<int:book_id>/', CartAddView.as_view(), name='add'),
    path('remove/<int:book_id>/', CartRemoveView.as_view(), name='remove'),
]

worldbook/catalog/urls.py
from django.urls import path
from catalog import views


app_name = 'catalog'
urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('search/', views.BookSearchView.as_view(), name='search'),
    path('book/<slug:book_slug>/', views.BookDetailView.as_view(), name='book'),
    path('<str:type>/<slug:slug>/', views.BookListView.as_view(), name='book_list'),
]

worldbook/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

worldbook/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users import views


app_name = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='main:home'), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password_change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

worldbook/worldbook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from worldbook import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/main/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    context = {
        'title': 'Главная страница',
        'content': 'Контент на главной странице',
    }

    return render(request, template_name='main/base.html', context=context)


def about(request):
    context = {
        'title': 'О нас',
        'content': 'Контент на странице о Нас!',
    }

    return render(request, template_name='main/about.html', context=context)

worldbook/templates/main/about.html
<!DOCTYPE html>
{% extends 'main/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{% block content %}
    {{ content }}
{% endblock %}
{{ content }}
</body>
</html>

worldbook/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/css/styles.css' %}">
    <title>{{ title }}</title>
</head>
<body>
{% block mainmenu %}
    <nav>
    <a href="{% url 'main:home' %}">Главная</a>
    |
    <a href="{% url 'catalog:catalog' %}">Каталог</a>
    |
    <a href="{% url 'cart:cart' %}">Корзина</a>
    |
    <a href="{% url 'blog:posts' %}">Статьи</a>
    |
    <a href="{% url 'main:about' %}">О нас</a>
    </nav>

    {% if user.is_authenticated %}
    <nav>
        <a href="{% url 'users:profile' %}">{{ user.username }}</a>
        |
        <a href="{% url 'users:logout' %}"
           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>
        <form id="logout-form" method="POST" style="display: none;" action="{% url 'users:logout' %}">
            {% csrf_token %}
        </form>
    </nav>
    {% else %}
    <nav>
        <a href="{% url 'users:login' %}">Войти</a>
        |
        <a href="{% url 'users:register' %}">Регистрация</a>
    </nav>
    {% endif %}

    <hr>
{% endblock %}

{% block seacrh %}
{% endblock %}

{% block cart %}
{% endblock %}

{% block content %}
<h1>Главная страница</h1>
{% endblock %}

{% block paginator %}
{% endblock %}
</body>
</html>