worldbook/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
]

worldbook/cart/urls.py
from django.urls import path
from .views import CartDetailView, CartAddView, CartRemoveView


app_name = 'cart'
urlpatterns = [
    path('', CartDetailView.as_view(), name='cart'),
    path('add/<int:book_id>/', CartAddView.as_view(), name='add'),
    path('remove/<int:book_id>/', CartRemoveView.as_view(), name='remove'),
]

worldbook/catalog/urls.py
from django.urls import path
from catalog import views


app_name = 'catalog'
urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('search/', views.BookSearchView.as_view(), name='search'),
    path('book/<slug:book_slug>/', views.BookDetailView.as_view(), name='book'),
    path('<str:type>/<slug:slug>/', views.BookListView.as_view(), name='book_list'),
]

worldbook/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/worldbook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from worldbook import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/catalog/models.py
from django.db import models
from django.urls import reverse
from PIL import Image as PilImage


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='URL-адрес')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    icon = models.ImageField(upload_to='category_icons/', blank=True, null=True, verbose_name='Иконка')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:book_list', kwargs={'slug': self.slug, 'type': 'category'})


class Genre(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='URL-адрес')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    icon = models.ImageField(upload_to='genre_icons/', blank=True, null=True, verbose_name='Иконка')

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:book_list', kwargs={'slug': self.slug, 'type': 'genre'})


class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='URL-адрес')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    icon = models.ImageField(upload_to='tag_icons/', blank=True, null=True, verbose_name='Иконка')

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:book_list', kwargs={'slug': self.slug, 'type': 'tag'})


class Author(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя', help_text='Введите имя автора')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия', help_text='Введите фамилию автора')
    photo = models.ImageField(upload_to='author_photos/', blank=True, null=True, verbose_name='Фотография')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='URL-адрес')
    biography = models.TextField(verbose_name='Биография', help_text='Краткая биография автора', blank=True)

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('catalog:book_list', kwargs={'slug': self.slug, 'type': 'author'})

    def get_type(self):
        return "Author"


class Book(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название', help_text="Введите название книги")
    slug = models.SlugField(max_length=250, unique=True, verbose_name='URL-адрес')
    image = models.ImageField(upload_to='cover_images/', blank=True, null=True, verbose_name='Обложка')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    year = models.PositiveIntegerField(verbose_name='Год издания')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, related_name='books', verbose_name='Категория')
    genre = models.ManyToManyField(Genre, blank=True, related_name='books', verbose_name='Жанр')
    authors = models.ManyToManyField(Author, blank=True, related_name='books', verbose_name='Автор(ы)')
    tags = models.ManyToManyField(Tag, blank=True, related_name='books', verbose_name='Тэг')
    isbn = models.CharField(max_length=50, blank=True, null=True, verbose_name='ISBN')
    pages = models.PositiveIntegerField(null=True, blank=True, verbose_name='Количество страниц')
    language = models.CharField(max_length=100, blank=True, verbose_name='Язык')
    publisher = models.CharField(max_length=200, blank=True, null=True, verbose_name='Издательство')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name='Цена')
    format = models.CharField(max_length=100, blank=True, null=True, verbose_name='Формат')
    added_on = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    updated_on = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    is_available = models.BooleanField(default=True, verbose_name='В наличии')

    class Meta:
        ordering = ['name']
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('catalog:book', kwargs={'book_slug': self.slug})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img_path = self.image.path
            img = PilImage.open(img_path)

            # Уменьшаем изображение, сохраняя пропорции
            img.thumbnail((300, 300), PilImage.Resampling.LANCZOS)

            # Если вы хотите обрезать изображение до точного размера 300x300 после уменьшения
            width, height = img.size  # Получаем размеры после уменьшения
            if width != 300 or height != 300:
                # Находим центральную точку
                left = (width - 300) / 2
                top = (height - 300) / 2
                right = (width + 300) / 2
                bottom = (height + 300) / 2

                # Обрезаем изображение до центральных 300x300
                img = img.crop((left, top, right, bottom))

            # Сохраняем изменения
            img.save(img_path)

worldbook/catalog/views.py
from django.db.models import Prefetch
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from catalog.models import Category, Book, Genre, Tag, Author
from .utils import BookFilter, search_book
from django.http import Http404
from cart.forms import CartAddBookForm


MODEL_MAP = {
        'category': Category,
        'genre': Genre,
        'tag': Tag,
        'author': Author,
    }


class CatalogView(ListView):
    model = Book
    template_name = 'catalog/catalog.html'
    context_object_name = 'books'
    paginate_by = 10
    extra_context = {
        'title': 'Каталог',
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filter = BookFilter(self.request.GET, queryset=queryset)
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filter
        return context


class BookListView(ListView):
    model = Book
    template_name = 'catalog/book_list.html'
    context_object_name = 'books'
    paginate_by = 3

    def get_queryset(self):
        type = self.kwargs.get('type').lower()
        slug = self.kwargs.get('slug')

        model = MODEL_MAP.get(type)
        if not model:
            raise Http404("Type not found")

        obj = get_object_or_404(model.objects.prefetch_related(
            Prefetch('books', queryset=Book.objects.all())
        ), slug=slug)

        return obj.books.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        type = self.kwargs.get('type').lower()
        slug = self.kwargs.get('slug')
        model = MODEL_MAP.get(type)
        obj = get_object_or_404(model, slug=slug)
        context['content'] = obj
        context['title'] = obj
        return context


class BookDetailView(DetailView):
    model = Book
    template_name = 'catalog/product.html'
    context_object_name = 'book'
    slug_url_kwarg = 'book_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        context['cart_form'] = CartAddBookForm()
        return context


class BookSearchView(ListView):
    model = Book
    template_name = 'catalog/search_book.html'
    context_object_name = 'content'
    paginate_by = 1

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            results = search_book(query)
        else:
            results = Book.objects.none()
        return results

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Поиск'
        return context

worldbook/templates/catalog/book_list.html
{% extends 'catalog/catalog.html' %}

{% block content %}
{% if content.get_type == 'Author' %}
    <h1>{{ content }}</h1>

    {% if content.photo %}
    <img src="{{ content.photo.url }}">
    {% endif %}

    <h2>Биография</h2>
    {{ content.biography }}

    <h2>Книги</h2>
    {% if books %}
        {% for book in books %}
            <p><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></p>
            {% if book.image %}
                <a href="{{ book.get_absolute_url }}"><img src="{{ book.image.url }}" alt="{{ book.title }}"></a>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>Книги не указаны</p>
    {% endif %}


{% else %}
    <h1>{{ content.name }}</h1>

    {% if content.icon %}
        <img src="{{ content.icon.url }}">
    {% endif %}

    <h2>Описание</h2>
    {{ content.description }}

    <h2>Книги</h2>
    {% if books %}
        {% for book in books %}
            <p><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></p>
            {% if book.image %}
                <a href="{{ book.get_absolute_url }}"><img src="{{ book.image.url }}" alt="{{ book.title }}"></a>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>Книги не указаны</p>
    {% endif %}
{% endif %}
{% endblock %}

worldbook/templates/catalog/catalog.html
{% extends 'main/base.html' %}


{% block seacrh %}
<form action="{% url 'catalog:search' %}" method="get">
    <input type="text" name="q" placeholder="Поиск...">
    <button type="submit">Поиск</button>
</form>
<hr>
{% endblock %}

{% block cart %}
{% with total_items=cart|length %}
    {% if total_items > 0 %}
        Ваша корзина:
        <a href="{% url 'cart:cart' %}">
            {{ total_items}} Книга |
            Тенге: {{ cart.get_total_price }}
        </a>
    {% else %}
        Корзина пуста
    {% endif %}
{% endwith %}
<hr>
{% endblock %}

{% block content %}
<form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Фильтровать</button>
    <a href="{% url 'catalog:catalog' %}">Очистить</a>
    <hr>
</form>


{% for book in books %}
    <p><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></p>
    <a href="{{ book.get_absolute_url }}"><img src="{{ book.image.url }}" alt="{{ book.name }}"></a>
{% empty %}
    <p>Книги не найдены.</p>
{% endfor %}

{% endblock %}


{% block paginator %}
{% if page_obj.has_other_pages %}
<nav><ul>
    {% if page_obj.has_previous %}
        <li>
            <li>
            <a href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}">&lt;</a>
        </li>
    {% endif %}

    {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
            <li class="page-num page-num-selected">{{ p }}</li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
           <li class="page-num"><a href="?{{ request.GET.urlencode }}&page={{ p }}">{{ p }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li><a href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">&gt;</a></li>
    {% endif %}
</ul></nav>
{% endif %}
{% endblock %}

worldbook/templates/catalog/product.html
{% extends 'catalog/catalog.html' %}
{% load static %}


{% block content %}
    <h1>{{ book.name }}</h1>

    <p> <img src="{{ book.image.url }}"></p>

    <h2>Описание</h2>
    <p>{{ book.description }}</p>

    <h2>Характеристики</h2>
    Год издания: {{ book.year }}

    {% if book.authors %}
        <p>Автор:
            {% for author in book.authors.all %}
                <a href="{{ author.get_absolute_url }}">{{ author }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% else %}
        <p>Авторы не указаны</p>
    {% endif %}

    <p>Категория: <a href="{{ book.category.get_absolute_url }}">{{ book.category }}</a></p>

    {% if book.genre %}
        <p>Жанры:
            {% for genre in book.genre.all %}
                <a href="{{ genre.get_absolute_url }}">{{ genre }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% else %}
        <p>Жанры не указаны</p>
    {% endif %}

    {% if book.tags %}
        <p>Тэги:
            {% for tag in book.tags.all %}
                <a href="{{ tag.get_absolute_url }}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% else %}
        <p>Тэги не указаны</p>
    {% endif %}

    ISBN: {{ book.isbn }}

    <p>Страницы : {{ book.pages }}</p>

    <p>Язык: {{ book.language }}</p>

    <p>Издатель: {{ book.publisher }}</p>

    <p>Размер: {{ book.format }}</p>

    <h2>Цена</h2>
    <p>Тенге: {{ book.price }}</p>
    <form action="{% url 'cart:add' book.id %}" method="post">
        {{ cart_form }}
        {% csrf_token %}
        <button type="submit">Добавить в корзину</button>
    </form>
{% endblock %}


{% block paginator %}
{% endblock %}

worldbook/templates/catalog/search_book.html
{% extends 'catalog/catalog.html' %}


{% block content %}
{% for book in content %}
    <p><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></p>
    <a href="{{ book.get_absolute_url }}"><img src="{{ book.image.url }}" alt="Обложка книги"></a>
{% empty %}
    <p>Книги не найдены.</p>
{% endfor %}
{% endblock %}