worldbook/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
]

worldbook/cart/urls.py
from django.urls import path
from .views import CartDetailView, CartAddView, CartRemoveView


app_name = 'cart'
urlpatterns = [
    path('', CartDetailView.as_view(), name='cart'),
    path('add/<int:book_id>/', CartAddView.as_view(), name='add'),
    path('remove/<int:book_id>/', CartRemoveView.as_view(), name='remove'),
]

worldbook/catalog/urls.py
from django.urls import path
from catalog import views


app_name = 'catalog'
urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('search/', views.BookSearchView.as_view(), name='search'),
    path('book/<slug:book_slug>/', views.BookDetailView.as_view(), name='book'),
    path('<str:type>/<slug:slug>/', views.BookListView.as_view(), name='book_list'),
]

worldbook/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/orders/urls.py
from django.urls import path
from .views import OrderCreateView, OrderCreatedView


app_name = 'orders'
urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('created/', OrderCreatedView.as_view(), name='created'),
]

worldbook/worldbook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from worldbook import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddBookForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label='Количество',
    )
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

worldbook/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, View
from cart.cart import Cart
from catalog.models import Book
from .forms import CartAddBookForm


class CartDetailView(TemplateView):
    template_name = 'cart/detail.html'
    extra_context = {
        'title': 'Корзина',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        for item in cart:
            item['update_quantity_form'] = CartAddBookForm(initial={
                'quantity': item['quantity'],
                'override': True})

        context['cart'] = cart
        return context


class CartAddView(View):
    def post(self, request, book_id):
        cart = Cart(request)
        book = get_object_or_404(Book, id=book_id)
        form = CartAddBookForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(book=book, quantity=cd['quantity'], override_quantity=cd['override'])

        return redirect('cart:cart')


class CartRemoveView(View):
    def post(self, request, book_id):
        cart = Cart(request)
        book = get_object_or_404(Book, id=book_id)
        cart.remove(book)
        return redirect('cart:cart')

worldbook/templates/cart/detail.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<h1>Корзина</h1>

<table>
    <thead>
    <tr>
        <th>Обложка</th>
        <th>Название</th>
        <th>Количество</th>
        <th>Цена за штуку</th>
        <th>Общая цена</th>
        <th>Удалить</th>
    </tr>
    </thead>

    <tbody>
    {% for item in cart %}
        {% with book=item.book %}
            <tr>
                <td>
                    <a href="{{ book.get_absolute_url }}">
                        <img src="{% if book.image %}{{ book.image.url }}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}">
                    </a>
                </td>
                <td>{{ book.name }}</td>
                <td>
                    <form action="{% url 'cart:add' book.id %}" method="post">
                        {% csrf_token %}
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <button type="submit">Изменить</button>
                    </form>
                </td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td>
                    <form action="{% url 'cart:remove' book.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Удалить</button>
                    </form>
                </td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr>
        <td>Итого</td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<hr>

<li><a href="{% url 'catalog:catalog' %}">Продолжить покупки</a></li>
<li><a href="{% url 'orders:create' %}">Оплатить счёт</a></li>
{% endblock %}