worldbook/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
]

worldbook/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from users import views


app_name = 'users'
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='main:home'), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password_change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

worldbook/worldbook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from worldbook import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worldbook/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография")

worldbook/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from captcha.fields import CaptchaField


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput())
    email = forms.CharField(disabled=True, required=False, label='E-mail', widget=forms.EmailInput())

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
        }


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput())
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput())
    captcha = CaptchaField()

    class Meta:
        model = get_user_model()
        fields = ['username', 'password', 'captcha']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput())
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())
    captcha = CaptchaField()

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'captcha']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.EmailInput(),
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput())
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput())
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput())

worldbook/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from worldbook import settings
from users.forms import ProfileUserForm, LoginUserForm, RegisterUserForm, UserPasswordChangeForm


# Create your views here.
class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Авторизация',
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {
        'title': 'Регистрация',
    }
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': "Профиль пользователя",
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}

worldbook/templates/users/login.html
{% extends 'main/base.html' %}


{% block content %}
<h2>Авторизация</h2>

<form method="post">
    {% csrf_token %}

    <div>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label>{{ f.label }} </label>{{ f }}</p>
    <div>{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Войти</button></p>
</form>

<hr>
<p><a href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/github.png"></a></p>

<hr>
<p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
{% endblock %}

worldbook/templates/users/password_change_done.html
{% extends 'main/base.html' %}


{% block content %}
<h1>Пароль успешно изменен!</h1>

<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

worldbook/templates/users/password_change_form.html
{% extends 'main/base.html' %}


{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Изменить пароль</button></p>
</form>
{% endblock %}

worldbook/templates/users/password_reset_complete.html
{% extends 'main/base.html' %}


{% block content %}
<h1>Пароль изменен</h1>

<p >Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>
{% endblock %}

worldbook/templates/users/password_reset_confirm.html
{% extends 'main/base.html' %}


{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}

    <div>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label>{{ f.label }} </label>{{ f }}</p>
    <div>{{ f.errors }}</div>
    {% endfor %}

    <p ><button type="submit">Сохранить</button></p>
</form>
{% endblock %}

worldbook/templates/users/password_reset_done.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p >{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
<p >{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

worldbook/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

worldbook/templates/users/password_reset_form.html
{% extends 'main/base.html' %}


{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}

    {% for f in form %}
    <p><label>{{ f.label }} </label>{{ f }}</p>
    <div>{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>
{% endblock %}

worldbook/templates/users/profile.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Профиль</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if user.photo %}
    <p><img src="{{ user.photo.url }}">
    {% else %}
    <p><img src="/{{ default_image }}">
    {% endif %}

    <div>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label>{{ f.label }} </label>{{ f }}</p>
    <div>{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Сохранить</button>
</form>

{% if not perms.users.social_auth %}
<hr>
<p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
{% endif %}

{% endblock %}

worldbook/templates/users/register.html
{% extends 'main/base.html' %}


{% block content %}
<h2>Регистрация</h2>

<form method="POST">
    {% csrf_token %}

    <div>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label>{{ f.label }} </label>{{ f }}</p>
    <div>{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Зарегистрироваться</button></p>
</form>
{% endblock %}